server {
    server_name  esamasiv.com;

    root   /usr/share/nginx/esamasiv;
    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ =404;
    }
    error_page 404 /404.html;
    error_page 500 502 503 504 /50x.html;

    location = /50x.html {
        root /usr/share/nginx/esamasiv;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/esamasiv.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/esamasiv.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}server {
    if ($host = esamasiv.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen       80;
    server_name  esamasiv.com;
    return 404; # managed by Certbot


}